### ISSUE TITLE
Demo app doesnt work

### ISSUE THREAD

**Issue by Kaloriya** [AprilBrother/ios-blueduino#1]
Hello Iam use this BlueDuino: http://ru.aliexpress.com/item/Apple-cetficate-Bluetooth4-0-low-energy-module-iBeacon-with-case/2024587044.html 

I tried to upload ABControllerSketch and ABStandFirmataSketch - but nothing works

Base IOS application (BlueDuino) find my BlueDuino controler but when I open it (Zerobeacon) - I see a white screen...

Can you help me???

**Comment by daisysomus** [comment]
Can you upload some screenshots?

**Comment by Kaloriya** [comment]
yes, it still doestn work
![img_0315](https://cloud.githubusercontent.com/assets/9746113/5110631/f50d1ed4-7022-11e4-9df6-0886c0e7b19f.PNG)
![img_0316](https://cloud.githubusercontent.com/assets/9746113/5110632/f50eb55a-7022-11e4-95c6-bc5fa83fa761.PNG)
![img_0314](https://cloud.githubusercontent.com/assets/9746113/5110633/f51225a0-7022-11e4-95ee-accd0be9fba5.JPG)

**Comment by daisysomus** [comment]
you can debug the app and check whether the app receives data from duino.

**Comment by Kaloriya** [comment]
can you explain me how can i do that? maybe you can give me a link with description of this process?

**Comment by daisysomus** [comment]
Maybe you can add me in skype. my skype account is veronicaljh.

**Comment by Kaloriya** [comment]
ok, i add you, can you add me (skype: Shabmaster)???
